# Generated by Django 3.2 on 2024-10-31 14:30

from django.db import migrations, models
import users.uuids


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='code',
            field=models.CharField(default=users.uuids.generate_short_uuid, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
