# Generated by Django 3.2 on 2024-11-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20241110_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='bio',
            field=models.TextField(default='', verbose_name='биография'),
        ),
    ]
