# Generated by Django 3.2 on 2024-11-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_myuser_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='admin',
            new_name='is_admin',
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
