# Generated by Django 3.2 on 2024-11-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20241103_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_moderator',
        ),
        migrations.AddField(
            model_name='myuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'USER'), ('moderator', 'MODERATOR'), ('admin', 'ADMIN')], default='user', max_length=20),
        ),
    ]
