# Generated by Django 3.2 on 2024-11-10 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_myuser_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ('id',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
