# Generated by Django 3.2 on 2024-11-11 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'default_related_name': 'reviews', 'ordering': ('-pub_date',), 'verbose_name': ('Отзыв',), 'verbose_name_plural': 'Отзывы'},
        ),
    ]
